### ISSUE TITLE
Unable to resolve "reactotron-core-client"

### ISSUE THREAD

**Issue by wellmonge** [infinitered/reactotron-redux#10]
I started configure the reactotron-redux in a pre existing application setup with redux and sagas, and get this error after configures reactotron as the code below.

`import { reactotronRedux } from "reactotron-redux";`
`import sagaPlugin from 'reactotron-redux-saga'`
```
const reactotron = Reactotron
  .configure({ name: 'My Pre Existing App' })
  .use(reactotronRedux())
  .use(sagaPlugin()) // <-- sweet
  .connect()
```
`export default reactotron
`

Print error:
![image](https://user-images.githubusercontent.com/5003655/54016442-b244d780-4161-11e9-9106-2471787851ed.png)

**Comment by rmevans9** [comment]
Can you show your import for Reactotron? (Mainly to see if you are using reactotron-react-js or reactotron-react-native)

**Comment by wellmonge** [comment]
> Can you show your import for Reactotron? (Mainly to see if you are using reactotron-react-js or reactotron-react-native)

I'm using reactotron-react-native, I resolved the issue by downgrade the reactotron-redux.

**Comment by rmevans9** [comment]
Can you confirm for me the version of `reactotron-core-client` that is installed in your project?

**Comment by wellmonge** [comment]
> Can you confirm for me the version of `reactotron-core-client` and `reactotron-react-native` that is installed in your project?

reactotron-core-client 2.7.0 and reactotron-react-native 3.2.1

**Comment by wellmonge** [comment]
Now I'm getting this error
![image](https://user-images.githubusercontent.com/5003655/57569916-754fc800-73d2-11e9-8d2e-13e484010c3d.png)

**Comment by rmevans9** [comment]
What version of redux-saga are you using?

**Comment by wellmonge** [comment]
> What version of redux-saga are you using?

I'm already try 4.0.0, 4.2.0 and 4.2.2...

**Comment by rmevans9** [comment]
The later versions of reactotron-redux-saga only work on redux-saga 1+. You can either downgrade reactotron-redux-saga or upgrade redux-saga :)

**Comment by wellmonge** [comment]
> The later versions of reactotron-redux-saga only work on redux-saga 1+. You can either downgrade reactotron-redux-saga or upgrade redux-saga :)
Okay! I'm going to put right versions for those dependecies.
I'm closing this issue, perhpas would be greate we have at docs a table of versions from reactotron-redux-saga -> redux-saga. I'm able to help on this if you wish!

**Comment by rmevans9** [comment]
That would be fantastic if you want to help put that together.
