### ISSUE TITLE
Typescript types file "reactotron-redux.d.ts" is absent

### ISSUE THREAD

**Issue by aarondail** [infinitered/reactotron-redux#4]
In the package.json, there is a "types" entry which points to a "reactotron-redux.d.ts" file, but that file is absent (in the repo itself and in the package published to npm).

Is this intentional?  I am happy to submit a PR adding it back, if you can give me a pointer as to when/where to find it... Maybe it was lost in the move from the main infinitered/reactotron repo?

**Comment by rmevans9** [comment]
I believe this was lost in the transition. I will be working to write this entire library in TypeScript in the coming days so I will be sure to resolve this issue along with that. 

Thanks for letting me know!

**Comment by rmevans9** [comment]
Its back in v3.0.0! :tada:
