### ISSUE TITLE
Compatibility with `redux.createStore`

### ISSUE THREAD

**Issue by SimonDegraeve** [infinitered/reactotron-redux#6]
The definition of the `redux` version of `createStore` is:

```js
createStore(reducer, [preloadedState], [enhancer])
```

Both `preloadedState` and `enhancer` are optional. However in the `reactotron` version, the function throws if there is no `enhancer`.

**Comment by rmevans9** [comment]
This is no longer an issue with Version 3.0.0 as we no longer require you to use the `createStore` on reactotron (infact there is no `createStore` on reactotron anymore!)

https://github.com/infinitered/reactotron-redux/releases/tag/v3.0.0
docs: https://github.com/infinitered/reactotron/blob/master/docs/plugin-redux.md
