### ISSUE TITLE
Android production build - null is not an object (evaluating 's.getState')

### ISSUE THREAD

**Issue by LuckyLuky** [infinitered/reactotron-redux#8]
Might seem like a duplicate of #317, but this is actually a separate issue. 

Once I import the Reactotron instance to my index file, although I use it to create store conditionally, inside `if (__DEV)` condition, the app immediately crashes. 

I've figured out that if I initialize Reactotron inside a factory function, which I call inside the `__DEV__` condition, everything works fine. 

The original config looks like this: 

```javascript
const reactotron
    .configure()
    .useReactNative()
    .use(reactotronRedux())
    .connect()

export default reactotron
```

With factory function:
```javascript
export const initReactotron = () => (
  Reactotron
    .configure()
    .useReactNative()
    .use(reactotronRedux())
    .connect()
)
```

I suspect that reactotronRedux plugin could be the reason.

**Comment by nicholascm90** [comment]
thank you @LuckyLuky - this is only way I could get this working.

**Comment by rmevans9** [comment]
This was caused because the store was trying to be used before everything was wired up. v3.0.0 has a guard against this so this should no longer happen!
